# Generated by Django 3.1.1 on 2020-10-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('position', models.CharField(max_length=3)),
                ('preferredFoot', models.CharField(max_length=5)),
                ('appearances', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
            ],
        ),
    ]
