# Generated by Django 3.1.1 on 2020-10-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_player_kitnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['kitNumber']},
        ),
    ]
