# Generated by Django 3.1.1 on 2020-10-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='kitNumber',
            field=models.IntegerField(verbose_name='Kit Number'),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferredFoot',
            field=models.CharField(max_length=5, verbose_name='Preferred Foot'),
        ),
    ]
