# Generated by Django 3.1.1 on 2020-10-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_stats_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='appearances',
        ),
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('DEF', 'Defender'), ('MID', 'Midfielder'), ('FW', 'Forward')], default='GK', max_length=3),
        ),
        migrations.AlterField(
            model_name='player',
            name='preferredFoot',
            field=models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('B', 'Both')], default='R', max_length=1, verbose_name='Preferred Foot'),
        ),
    ]
