# Generated by Django 3.1.1 on 2020-10-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201008_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='training',
            new_name='trainings',
        ),
    ]
